### ISSUE TITLE
Sets incorrect parser while using CSS-in-JS with JS Custom syntax highlighting

### ISSUE THREAD

**Issue by hudochenkov** [jonlabelle/SublimeJsPrettier#150] opened 2019-01-11 19:11 UTC
### Explain the Issue and Expected Behavior

JsPrettier sets incorrect parser for JavaScript file (.js), when a cursor inside Styled Component CSS, and [JS Custom](https://github.com/Thom1729/Sublime-JS-Custom) syntax highlighting is used with [styled components support](https://github.com/Thom1729/Sublime-JS-Custom#styled_components-boolean) enabled.

### Prettier version

1.15.3

### JsPrettier Plug-in Version

1.21.7

### Platform Details

Sublime Text 3 Build 3184 (dev). macOS 10.14.1

### Generated Prettier command line arguments

```
JsPrettier [DEBUG]: Prettier config file not found. Will use Prettier options defined in Sublime Text 'JsPrettier.sublime-settings' file.

-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/Users/ahudochenkov/Downloads/untitled folder/node_modules/.bin/prettier --stdin --no-config --print-width 100 --single-quote true --trailing-comma es5 --bracket-spacing true --jsx-bracket-same-line false --parser css --semi true --require-pragma false --prose-wrap preserve --arrow-parens avoid --html-whitespace-sensitivity css --tab-width 4 --use-tabs true --stdin-filepath /Users/ahudochenkov/Downloads/untitled folder/test.js --cursor-offset 81

------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error(s):

[error] stdin: SyntaxError: (postcss) CssSyntaxError Unknown word (1:1)
[error] > 1 | import styled from 'styled-components';
[error]     | ^
[error]   2 | 
[error]   3 | const Test = styled.div`
[error]   4 |   display:none;

Process finished with exit code 2
```

### Is the same behavior observed when run against Prettier directly?

Yes.

### The contents of your `User/JsPrettier.sublime-settings` file

```json
{
	"prettier_cli_path": "/Users/ahudochenkov/Downloads/untitled folder/node_modules/.bin/prettier",
	"debug": true,
	"allow_inline_formatting": true,
	"prettier_options": {
		"proseWrap": "preserve",
		"printWidth": 100,
		"singleQuote": true,
		"trailingComma": "es5"
	}
}
```

### Steps to reproduce the behavior

JsPrettier sets incorrect parser for JavaScript file (.js), when a cursor inside Styled Component CSS, and [JS Custom](https://github.com/Thom1729/Sublime-JS-Custom) syntax highlighting is used with [styled components support](https://github.com/Thom1729/Sublime-JS-Custom#styled_components-boolean) enabled.

1. Install [JS Custom](https://github.com/Thom1729/Sublime-JS-Custom) syntax highlighting, and enable [styled components support](https://github.com/Thom1729/Sublime-JS-Custom#styled_components-boolean).
2. Open any JavaScript file with styled components. E. g.:

	```js
	import styled from 'styled-components';

	const Test = styled.div`
	  display:none;
	`;
	```

3. Put cursor after `display:none;`, and run JsPrettier.

The problem is JsPrettier doesn't know enough about syntax scope which is set for CSS part of the file. It detects syntax CSS and sets it for the whole file. But file is JavaScript, so Prettier use wrong parser.

Scope is `source.css.embedded.js meta.property-list.css`.

Issue is important, because it will affect babel-sublime users soon. JS Custom [is going to replace babel-sublime](https://github.com/babel/babel-sublime/issues/355).

P. S. I spent much more time composing this issue, then making a PR with fix :)

[debug setting]: https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L14

**Comment by mohitsinghs** [comment] 2019-01-12 09:16
Until the PR gets merged, I've added your changes along with mine in [a fork](https://github.com/subpack/SublimeJsPrettier). Thanks @hudochenkov

**Comment by Thom1729** [comment] 2019-01-13 22:40
It looks like this may be due to [PR #55](https://github.com/Thom1729/Sublime-JS-Custom/pull/55). Before that PR, Styled Components templates were `source.js ... source.css.embedded.js`. Emmet had trouble with this, so it was changed to clear all of the JS scopes. The solution would most likely be to revert to the original behavior by default and add an option to clear the JS scopes.

PR #151 looks like it would work, but if the regression breaks this, it probably breaks some other package that's less actively maintained. Whenever possible, JS Custom should support by default tools designed for the core JavaScript syntax.

**Closed** 2019-01-21 01:51 UTC
